import {
  REPAIR_CATEGORIES,
  REPAIR_OWNERS,
  REPAIR_SEVERITIES,
  type RepairBurden,
  type StageSSuiteResult,
  type StageSValidationResult,
} from "./types";

/**
 * Deterministic Stage S report generators.
 *
 * Pure string producers — no filesystem, no clock. The suite's injected
 * `generatedAt` is the only time source, keeping reports byte-stable so the
 * committed artifacts can be gate-checked against freshly generated output.
 */

function severityLine(burden: RepairBurden): string {
  return REPAIR_SEVERITIES.map((severity) => `${severity} ${burden.bySeverity[severity]}`).join(" · ");
}

function nonZeroCategoryRows(burden: RepairBurden): string[] {
  return REPAIR_CATEGORIES.filter((category) => burden.byCategory[category] > 0).map(
    (category) => `| ${category} | ${burden.byCategory[category]} |`,
  );
}

function ownerRows(burden: RepairBurden): string[] {
  return REPAIR_OWNERS.map((owner) => `| ${owner} | ${burden.byOwner[owner]} |`);
}

function fixtureSection(result: StageSValidationResult): string {
  const status = result.pass ? "✅ PASS" : "❌ FAIL";
  const lines: string[] = [];
  lines.push(`### ${result.fixtureName} — ${status}`);
  lines.push("");
  lines.push(`- Transcript: \`${result.transcriptId}\``);
  lines.push(`- Paragraphs: ${result.burden.paragraphsTotal}`);
  lines.push(`- Repairs: ${result.burden.total} across ${result.burden.findingCount} finding(s) (${severityLine(result.burden)})`);
  lines.push(`- Repair density: ${result.burden.repairDensity} · Repair %: ${result.burden.repairPercentage}`);
  lines.push(`- Completeness: ${(result.completeness * 100).toFixed(2)}%`);
  lines.push(`- Pages (est.): ${result.upstream.pageCount}`);
  lines.push(
    `- Upstream: render-parity ${result.upstream.renderParityErrors.length === 0 ? "OK" : `${result.upstream.renderParityErrors.length} error(s)`} · export-contract ${result.upstream.exportContractValid ? "OK" : "REJECTED"}`,
  );
  if (result.findings.length > 0) {
    lines.push("");
    lines.push("| Severity | Category | Owner | Paragraph | Message |");
    lines.push("| --- | --- | --- | --- | --- |");
    for (const finding of result.findings) {
      lines.push(
        `| ${finding.severity} | ${finding.category} | ${finding.owner} | ${finding.paragraphId ?? "—"} | ${finding.message} |`,
      );
    }
  }
  if (result.appliedRepairs.length > 0) {
    lines.push("");
    lines.push("Deterministic Stage S presentation repairs applied:");
    for (const repair of result.appliedRepairs) {
      lines.push(`- ${repair.category}: ${repair.description} (${repair.count})`);
    }
  }
  return lines.join("\n");
}

export function generateValidationReport(suite: StageSSuiteResult): string {
  const { aggregate } = suite;
  const lines: string[] = [];
  lines.push("# Stage S Validation Report");
  lines.push("");
  lines.push("_Generated by the Stage S validation engine (PR #19). Measurement only — no upstream owner is modified._");
  lines.push("");
  lines.push(`- Generated at: ${suite.generatedAt}`);
  lines.push(`- Export contract version: ${suite.contractVersion}`);
  lines.push(`- Fixtures: ${aggregate.fixtures} · Passing: ${aggregate.passing} · Failing: ${aggregate.failing}`);
  lines.push(`- Total repairs: ${aggregate.totalRepairs} across ${aggregate.burden.findingCount} finding(s) (${severityLine(aggregate.burden)})`);
  lines.push(`- Release Candidate ready: ${aggregate.releaseCandidateReady ? "YES" : "NO"}`);
  lines.push("");
  lines.push("## Per-fixture results");
  lines.push("");
  for (const result of suite.results) {
    lines.push(fixtureSection(result));
    lines.push("");
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

export function generateRepairBurdenReport(suite: StageSSuiteResult): string {
  const { aggregate } = suite;
  const burden = aggregate.burden;
  const lines: string[] = [];
  lines.push("# Repair Burden Report");
  lines.push("");
  lines.push("_How much manual repair remains to certify the compiled transcript, and which owner is responsible._");
  lines.push("");
  lines.push(`- Generated at: ${suite.generatedAt}`);
  lines.push(`- Fixtures measured: ${aggregate.fixtures}`);
  lines.push(`- Total repairs: ${burden.total}`);
  lines.push(`- Critical: ${burden.bySeverity.CRITICAL} · Major: ${burden.bySeverity.MAJOR} · Minor: ${burden.bySeverity.MINOR} · Cosmetic: ${burden.bySeverity.COSMETIC}`);
  lines.push(`- Paragraphs affected: ${burden.paragraphsAffected}/${burden.paragraphsTotal} (${burden.repairPercentage}%)`);
  lines.push(`- Repair density: ${burden.repairDensity} findings/paragraph`);
  lines.push("");
  lines.push("## Repairs by category");
  lines.push("");
  lines.push("| Category | Count |");
  lines.push("| --- | --- |");
  const categoryRows = nonZeroCategoryRows(burden);
  lines.push(...(categoryRows.length > 0 ? categoryRows : ["| (none) | 0 |"]));
  lines.push("");
  lines.push("## Repairs by responsible owner");
  lines.push("");
  lines.push("| Owner | Count |");
  lines.push("| --- | --- |");
  lines.push(...ownerRows(burden));
  lines.push("");
  lines.push("## Certification readiness questions");
  lines.push("");
  lines.push(`- How many repairs remain before certification? **${burden.total}** (${burden.bySeverity.CRITICAL} critical).`);
  lines.push(`- What percentage of paragraphs require manual intervention? **${burden.repairPercentage}%**.`);
  lines.push(`- Is the current pipeline Release Candidate quality? **${aggregate.releaseCandidateReady ? "YES" : "NO"}**.`);
  return `${lines.join("\n").trimEnd()}\n`;
}

export function generateMetricsJson(suite: StageSSuiteResult): string {
  return `${JSON.stringify(suite, null, 2)}\n`;
}
