substitutions:
  _IMAGE: us-central1-docker.pkg.dev/depo-pro-website/depo-pro/depo-pro-formatter:manual

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - formatter_service/Dockerfile
      - --tag
      - ${_IMAGE}
      - .

images:
  - ${_IMAGE}
