function wrapped<T>(value: T, confidence = 1, inferred = false) {
  return { value, confidence, inferred };
}

export const GARZA_HEATH_THOMAS_RAW_FIXTURE = {
  cause_number: "25-cv-00598-OLG",
  case_style: "DELIA GARZA v. HOME DEPOT U.S.A., INC. A/K/A THE HOME DEPOT AND SHAWN HERBER",
  plaintiff: "Delia Garza",
  defendants: "[\"HOME DEPOT U.S.A., INC. A/K/A THE HOME DEPOT\", \"SHAWN HERBER\"]",
  court_name: "UNITED STATES DISTRICT COURT",
  district: "WESTERN DISTRICT OF TEXAS",
  division: "SAN ANTONIO DIVISION",
  county: "Bexar",
  state: "Texas",
  jurisdiction_type: "federal",
  deposition_date: "2026-04-30",
  start_time: "13:30",
  end_time: "",
  location: {
    address: "",
    city: "",
    state: "",
    zip: "",
  },
  remote: {
    is_remote: wrapped(true),
    platform: wrapped("Zoom"),
  },
  reporting_method: "zoom",
  witness: {
    name: wrapped("Heath Thomas"),
    role: wrapped(""),
    party_affiliation: wrapped(""),
    read_and_sign: wrapped(""),
    interpreter_required: wrapped(false),
    videographer_required: wrapped(false, 0.6, true),
  },
  parties: [
    {
      name: wrapped("Delia Garza"),
      role: wrapped("Plaintiff"),
      role_modifier: wrapped(""),
      entity_type: wrapped("Individual", 0.5, true),
      fka_or_dba: wrapped(""),
    },
    {
      name: wrapped("HOME DEPOT U.S.A., INC."),
      role: wrapped("Defendant"),
      role_modifier: wrapped(""),
      entity_type: wrapped("Corporation"),
      fka_or_dba: wrapped("THE HOME DEPOT"),
    },
    {
      name: wrapped("SHAWN HERBER"),
      role: wrapped("Defendant"),
      role_modifier: wrapped(""),
      entity_type: wrapped("Individual", 0.5, true),
      fka_or_dba: wrapped(""),
    },
  ],
  attorneys: [
    {
      name: wrapped("Jacob D. Cukjati"),
      firm: wrapped("CUKJATI LAW FIRM, PLLC"),
      representing: wrapped("Delia Garza"),
      address: wrapped("875 East Ashby Place, Ste. 1225"),
      city: wrapped("San Antonio"),
      state: wrapped("Texas"),
      zip: wrapped("78212"),
      phone: wrapped("726-239-4423"),
      email: wrapped("service@cukjati-law.com"),
      bar_number: wrapped("24101188"),
      side: wrapped("Plaintiff"),
    },
    {
      name: wrapped("Curtis L. Cukjati"),
      firm: wrapped("CUKJATI LAW FIRM, PLLC"),
      representing: wrapped("Delia Garza"),
      address: wrapped("875 East Ashby Place, Ste. 1225"),
      city: wrapped("San Antonio"),
      state: wrapped("Texas"),
      zip: wrapped("78212"),
      phone: wrapped("726-239-4423"),
      email: wrapped("service@cukjati-law.com"),
      bar_number: wrapped("05207540"),
      side: wrapped("Plaintiff"),
    },
    {
      name: wrapped("Steven A. Nunez"),
      firm: wrapped("BRAIN AND SPINE PERSONAL INJURY LAWYERS OF SAN ANTONIO, PLLC"),
      representing: wrapped("Delia Garza"),
      address: wrapped("8620 N New Braunfels Ave, Ste. N 604"),
      city: wrapped("San Antonio"),
      state: wrapped("Texas"),
      zip: wrapped("78217-4000"),
      phone: wrapped("(210) 999-5033"),
      email: wrapped("service@brainspine-law.com"),
      bar_number: wrapped("24107206"),
      side: wrapped("Plaintiff"),
    },
    {
      name: wrapped("Karen M. Alvarado"),
      firm: wrapped("BROTHERS, ALVARADO, PIAZZA & COZORT, P.C."),
      representing: wrapped("HOME DEPOT U.S.A., INC."),
      address: wrapped("10333 Richmond, Suite 900"),
      city: wrapped("Houston"),
      state: wrapped("Texas"),
      zip: wrapped("77042"),
      phone: wrapped("(713) 337-0750"),
      email: wrapped("SERVICE-ALVARADO@BROTHERS-LAW.COM"),
      bar_number: wrapped("", 0.5),
      side: wrapped("Defendant"),
    },
  ],
  law_firms: [
    {
      name: wrapped("CUKJATI LAW FIRM, PLLC"),
      address: wrapped("875 East Ashby Place, Ste. 1225"),
      city: wrapped("San Antonio"),
      state: wrapped("Texas"),
      zip: wrapped("78212"),
      phone: wrapped("726-239-4423"),
      fax: wrapped("726-256-5224"),
      email: wrapped("service@cukjati-law.com"),
      represented_party: wrapped("Delia Garza"),
    },
    {
      name: wrapped("BROTHERS, ALVARADO, PIAZZA & COZORT, P.C."),
      address: wrapped("10333 Richmond, Suite 900"),
      city: wrapped("Houston"),
      state: wrapped("Texas"),
      zip: wrapped("77042"),
      phone: wrapped("(713) 337-0750"),
      fax: wrapped("(713) 337-0760"),
      email: wrapped("SERVICE-ALVARADO@BROTHERS-LAW.COM"),
      represented_party: wrapped("HOME DEPOT U.S.A., INC."),
    },
  ],
  scheduling: {
    proceeding_type: wrapped("Oral Deposition"),
    remote_platform: wrapped("Zoom"),
    noticing_party: wrapped("Plaintiff, Delia Garza"),
    ordered_by: wrapped("Tiffany Netcher", 0.7, true),
    scheduler: wrapped("", 0.5),
    scheduling_contact: wrapped("", 0.5),
    service_type: wrapped("E-Tran", 0.6, true),
    time_zone: wrapped("Central Time"),
    remote_location: wrapped("", 0.5),
  },
  service: {
    certificate_of_service: wrapped(true),
    service_date: wrapped("2026-04-09"),
    served_parties: [
      "Karen M. Alvarado",
      "BROTHERS, ALVARADO, PIAZZA & COZORT, P.C.",
      "Steven A. Nunez",
    ],
    served_parties_confidence: 0.9,
    served_parties_inferred: false,
    service_emails: [
      "SERVICE-ALVARADO@BROTHERS-LAW.COM",
      "service@brainspine-law.com",
    ],
    service_emails_confidence: 0.8,
    service_emails_inferred: false,
  },
  reporter_requests: {
    certified_reporter_required: wrapped(true),
    stenographic_recording: wrapped(true),
    audiovisual_recording: wrapped(true, 0.9),
    realtime_requested: wrapped(false, 0.5, true),
    expedited_delivery: wrapped(false, 0.5, true),
    rush_delivery: wrapped(false, 0.5, true),
    daily_copy: wrapped(false, 0.5, true),
    rough_draft: wrapped(false, 0.5, true),
  },
  other_participants: [],
};

export const GOLDMAN_MONTES_NAVARRO_RAW_FIXTURE = {
  cause_number: "C-1628-25-E",
  case_style: "MARIA L. LOPEZ DE MARTINEZ AND ALFREDO MONTES NAVARRO v. RAFAEL ROBLES CALDERON AND ALL AMERICAN HEAVY EQUIPMENT LEASING, LLC",
  plaintiff: "Maria L. Lopez De Martinez and Alfredo Montes Navarro",
  defendants: [
    "Rafael Robles Calderon",
    "All American Heavy Equipment Leasing, LLC",
  ],
  court_name: "275TH JUDICIAL DISTRICT COURT",
  district: "275TH JUDICIAL DISTRICT",
  division: "",
  county: "Hidalgo County",
  state: "Texas",
  jurisdiction_type: "texas_state",
  deposition_date: "2026-05-07",
  start_time: "14:00",
  end_time: "",
  location: {
    address: "",
    city: "San Antonio",
    state: "TX",
    zip: "",
  },
  remote: {
    is_remote: wrapped(true),
    platform: wrapped("Zoom"),
  },
  reporting_method: "zoom",
  witness: {
    name: wrapped("Alfredo Montes Navarro"),
    role: wrapped(""),
    party_affiliation: wrapped("Plaintiff"),
    read_and_sign: wrapped(""),
    interpreter_required: wrapped(false),
    videographer_required: wrapped(false),
  },
  parties: [
    { name: wrapped("Maria L. Lopez De Martinez"), role: wrapped("Plaintiff"), role_modifier: wrapped(""), entity_type: wrapped("Individual"), fka_or_dba: wrapped("") },
    { name: wrapped("Alfredo Montes Navarro"), role: wrapped("Plaintiff"), role_modifier: wrapped(""), entity_type: wrapped("Individual"), fka_or_dba: wrapped("") },
    { name: wrapped("Rafael Robles Calderon"), role: wrapped("Defendant"), role_modifier: wrapped(""), entity_type: wrapped("Individual"), fka_or_dba: wrapped("") },
    { name: wrapped("All American Heavy Equipment Leasing, LLC"), role: wrapped("Defendant"), role_modifier: wrapped(""), entity_type: wrapped("LLC"), fka_or_dba: wrapped("") },
  ],
  attorneys: [
    {
      name: wrapped("Raul Garza"),
      firm: wrapped("Goldman & Peterson, PLLC"),
      representing: wrapped("Rafael Robles Calderon and All American Heavy Equipment Leasing, LLC"),
      address: wrapped("10100 Reunion Place, Suite 800"),
      city: wrapped("San Antonio"),
      state: wrapped("TX"),
      zip: wrapped("78216"),
      phone: wrapped("(210) 340-9800"),
      email: wrapped("Raul@LJGLaw.com"),
      bar_number: wrapped(""),
      side: wrapped("Defendant"),
    },
    {
      name: wrapped("Derek I. Salinas"),
      firm: wrapped("Tijerina Legal Group, P.C."),
      representing: wrapped("Maria L. Lopez De Martinez and Alfredo Montes Navarro"),
      address: wrapped("1200 S. 2nd Street, Suite 4A"),
      city: wrapped("McAllen"),
      state: wrapped("TX"),
      zip: wrapped("78501"),
      phone: wrapped(""),
      email: wrapped("derek@tlegal.com"),
      bar_number: wrapped(""),
      side: wrapped("Plaintiff"),
    },
  ],
  law_firms: [],
  scheduling: {
    proceeding_type: wrapped("Amended Notice of Intention to Take Oral Deposition"),
    remote_platform: wrapped("Zoom"),
    noticing_party: wrapped("Defendant"),
    ordered_by: wrapped("Rose Soto-Oliveras"),
    scheduler: wrapped("Raul Garza"),
    scheduling_contact: wrapped("Raul@LJGLaw.com"),
    service_type: wrapped("E-Trans"),
    time_zone: wrapped("Central Time"),
    remote_location: wrapped("San Antonio, Texas"),
  },
  service: {
    certificate_of_service: wrapped(true),
    service_date: wrapped("2026-04-20"),
    served_parties: ["Counsel of Record"],
    served_parties_confidence: 0.9,
    served_parties_inferred: false,
    service_emails: ["Raul@LJGLaw.com", "derek@tlegal.com"],
    service_emails_confidence: 0.8,
    service_emails_inferred: false,
  },
  reporter_requests: {
    certified_reporter_required: wrapped(true),
    stenographic_recording: wrapped(true),
    audiovisual_recording: wrapped(true),
    realtime_requested: wrapped(false),
    expedited_delivery: wrapped(false),
    rush_delivery: wrapped(false),
    daily_copy: wrapped(false),
    rough_draft: wrapped(false),
  },
  other_participants: [],
};

export const HILL_BENITEZ_RAW_FIXTURE = {
  cause_number: "2025CI11923",
  case_style: "LOLA PAVAN, INDIVIDUALLY AND AS NEXT FRIEND OF A.S., A MINOR v. FRANK ECHEVARRIA BENITEZ D/B/A FEB TRANSPORT AND JUNIOR BENITEZ",
  plaintiff: "Lola Pavan, Individually and as Next Friend of A.S., a Minor",
  defendants: [
    "Frank Echevarria Benitez D/B/A FEB Transport",
    "Junior Benitez",
  ],
  court_name: "DISTRICT COURT",
  district: "408TH JUDICIAL DISTRICT",
  division: "",
  county: "Bexar County",
  state: "Texas",
  jurisdiction_type: "texas_state",
  deposition_date: "2026-04-16",
  start_time: "10:03",
  end_time: "11:49",
  location: {
    address: "2900 Blue Wing Road",
    city: "San Antonio",
    state: "Texas",
    zip: "",
  },
  remote: {
    is_remote: wrapped(true),
    platform: wrapped("Zoom"),
  },
  reporting_method: "zoom",
  witness: {
    name: wrapped("Frank Echevarria Benitez"),
    role: wrapped(""),
    party_affiliation: wrapped("Defendant"),
    read_and_sign: wrapped(""),
    interpreter_required: wrapped(true),
    videographer_required: wrapped(true),
  },
  parties: [
    { name: wrapped("Lola Pavan, Individually and as Next Friend of A.S., a Minor"), role: wrapped("Plaintiff"), role_modifier: wrapped(""), entity_type: wrapped("Individual"), fka_or_dba: wrapped("") },
    { name: wrapped("Frank Echevarria Benitez"), role: wrapped("Defendant"), role_modifier: wrapped(""), entity_type: wrapped("Individual"), fka_or_dba: wrapped("D/B/A FEB Transport") },
    { name: wrapped("Junior Benitez"), role: wrapped("Defendant"), role_modifier: wrapped(""), entity_type: wrapped("Individual"), fka_or_dba: wrapped("") },
  ],
  attorneys: [
    {
      name: wrapped("Gabriel Narvaez"),
      firm: wrapped("HILL LAW FIRM"),
      representing: wrapped("Lola Pavan, Individually and as Next Friend of A.S., a Minor"),
      address: wrapped("445 Recoleta Rd."),
      city: wrapped("San Antonio"),
      state: wrapped("Texas"),
      zip: wrapped("78216"),
      phone: wrapped("(210) 960-3939"),
      email: wrapped("Justin@jahlawfirm.com"),
      bar_number: wrapped(""),
      side: wrapped("Plaintiff"),
    },
    {
      name: wrapped("Chris Madrid"),
      firm: wrapped("Goldman & Peterson, PLLC"),
      representing: wrapped("Frank Echevarria Benitez and FEB Transport and Junior Benitez"),
      address: wrapped("10100 Reunion Place, Suite 800"),
      city: wrapped("San Antonio"),
      state: wrapped("Texas"),
      zip: wrapped("78216"),
      phone: wrapped("(210) 340-9800"),
      email: wrapped("Mail@LJGLaw.com"),
      bar_number: wrapped(""),
      side: wrapped("Defendant"),
    },
  ],
  law_firms: [],
  scheduling: {
    proceeding_type: wrapped("Oral and Videotaped Deposition"),
    remote_platform: wrapped("Zoom"),
    noticing_party: wrapped("Plaintiffs"),
    ordered_by: wrapped(""),
    scheduler: wrapped(""),
    scheduling_contact: wrapped(""),
    service_type: wrapped(""),
    time_zone: wrapped("Central Time"),
    remote_location: wrapped("San Antonio, Texas"),
  },
  service: {
    certificate_of_service: wrapped(false),
    service_date: wrapped(""),
    served_parties: [],
    served_parties_confidence: 0,
    served_parties_inferred: false,
    service_emails: [],
    service_emails_confidence: 0,
    service_emails_inferred: false,
  },
  reporter_requests: {
    certified_reporter_required: wrapped(true),
    stenographic_recording: wrapped(true),
    audiovisual_recording: wrapped(true),
    realtime_requested: wrapped(false),
    expedited_delivery: wrapped(false),
    rush_delivery: wrapped(false),
    daily_copy: wrapped(false),
    rough_draft: wrapped(false),
  },
  other_participants: [
    { name: wrapped("Mario Leal"), role: wrapped("Videographer") },
    { name: wrapped("Mauricio Dominguez"), role: wrapped("Interpreter") },
  ],
};
