import type { ExtractedNODFields } from "../aiExtractionTypes";

function field<T>(value: T | null, confidence = 0.9) {
  return { value, confidence };
}

function baseFixture(): ExtractedNODFields {
  return {
    cause_number: field(""),
    case_style: field(""),
    plaintiff: field(""),
    defendants: field<string[]>([]),
    court_name: field(""),
    district: field(""),
    division: field(""),
    county: field(""),
    state: field(""),
    jurisdiction_type: field(""),
    deposition_date: field(""),
    start_time: field(""),
    end_time: field(null),
    location: {
      address: field(""),
      city: field(""),
      state: field(""),
      zip: field(""),
    },
    remote: {
      is_remote: field(false),
      platform: field(""),
    },
    reporting_method: field(""),
    witness: {
      name: field(""),
      role: field("witness"),
      party_affiliation: field(""),
      read_and_sign: field(""),
      interpreter_required: field(null),
      videographer_required: field(null),
    },
    parties: [],
    attorneys: [],
    law_firms: [],
    scheduling: {
      proceeding_type: field(""),
      remote_platform: field(""),
      noticing_party: field(""),
      ordered_by: field(""),
      scheduler: field(""),
      scheduling_contact: field(""),
      service_type: field(""),
      time_zone: field(""),
      remote_location: field(""),
    },
    service: {
      certificate_of_service: field(null),
      service_date: field(""),
      served_parties: field<string[]>([]),
      service_emails: field<string[]>([]),
    },
    reporter_requests: {
      certified_reporter_required: field(null),
      stenographic_recording: field(null),
      audiovisual_recording: field(null),
      realtime_requested: field(null),
      expedited_delivery: field(null),
      rush_delivery: field(null),
      daily_copy: field(null),
      rough_draft: field(null),
    },
    other_participants: [],
  };
}

export const FEDERAL_NOD_FIXTURE: ExtractedNODFields = {
  ...baseFixture(),
  cause_number: field("25-cv-00598-OLG"),
  case_style: field("Delia Garza v. Home Depot U.S.A., Inc. A/K/A The Home Depot and Shawn Herber"),
  plaintiff: field("Delia Garza"),
  defendants: field(["Home Depot U.S.A., Inc. A/K/A The Home Depot", "Shawn Herber"]),
  court_name: field("United States District Court"),
  district: field("Western District of Texas"),
  division: field("San Antonio Division"),
  county: field("Bexar County"),
  state: field("Texas"),
  jurisdiction_type: field("federal"),
  deposition_date: field("2026-04-30"),
  start_time: field("13:30"),
  remote: { is_remote: field(true), platform: field("Zoom") },
  reporting_method: field("machine_shorthand"),
  witness: {
    name: field("Heath Thomas"),
    role: field("witness"),
    party_affiliation: field("defendant"),
    read_and_sign: field("waived"),
    interpreter_required: field(false),
    videographer_required: field(true),
  },
  parties: [
    { name: field("Delia Garza"), role: field("plaintiff"), role_modifier: field(null), entity_type: field("individual"), fka_or_dba: field(null) },
    { name: field("Home Depot U.S.A., Inc. A/K/A The Home Depot"), role: field("defendant"), role_modifier: field(null), entity_type: field("corporation"), fka_or_dba: field("A/K/A The Home Depot") },
    { name: field("Shawn Herber"), role: field("defendant"), role_modifier: field(null), entity_type: field("individual"), fka_or_dba: field(null) },
  ],
  attorneys: [
    {
      name: field("Justin C. Hill"),
      firm: field("Brothers, Alvarado, Piazza & Cozort, P.C."),
      representing: field("FOR PLAINTIFF DELIA GARZA"),
      address: field("123 Main Street"),
      city: field("San Antonio"),
      state: field("TX"),
      zip: field("78205"),
      phone: field("(210) 555-0199"),
      email: field("jhill@example.com"),
      bar_number: field("24012345"),
      side: field("plaintiff"),
    },
  ],
  law_firms: [
    {
      name: field("Brothers, Alvarado, Piazza & Cozort, P.C."),
      address: field("123 Main Street"),
      city: field("San Antonio"),
      state: field("TX"),
      zip: field("78205"),
      phone: field("(210) 555-0199"),
      fax: field("(210) 555-0188"),
      email: field("service@example.com"),
      represented_party: field("Plaintiff"),
    },
  ],
  scheduling: {
    proceeding_type: field("Oral and Videotaped Deposition"),
    remote_platform: field("Zoom"),
    noticing_party: field("Plaintiff"),
    ordered_by: field("Brothers, Alvarado, Piazza & Cozort, P.C."),
    scheduler: field("Scheduling Coordinator"),
    scheduling_contact: field("service@example.com"),
    service_type: field("CR_plus_Zoom"),
    time_zone: field("Central"),
    remote_location: field("San Antonio, Texas"),
  },
  service: {
    certificate_of_service: field(true),
    service_date: field("2026-04-10"),
    served_parties: field(["Plaintiff", "Defendants"]),
    service_emails: field(["service@example.com", "defense@example.com"]),
  },
  reporter_requests: {
    certified_reporter_required: field(true),
    stenographic_recording: field(true),
    audiovisual_recording: field(true),
    realtime_requested: field(false),
    expedited_delivery: field(false),
    rush_delivery: field(false),
    daily_copy: field(false),
    rough_draft: field(false),
  },
};

export const TEXAS_STATE_NOD_FIXTURE: ExtractedNODFields = {
  ...baseFixture(),
  cause_number: field("C-1628-25-E"),
  case_style: field("Maria L. Lopez De Martinez and Alfredo Montes Navarro v. Rafael Robles Calderon and All American Heavy Equipment Leasing, LLC"),
  plaintiff: field("Maria L. Lopez De Martinez and Alfredo Montes Navarro"),
  defendants: field(["Rafael Robles Calderon", "All American Heavy Equipment Leasing, LLC"]),
  court_name: field("275th Judicial District Court"),
  district: field("275th Judicial District"),
  division: field(""),
  county: field("Hidalgo County"),
  state: field("Texas"),
  jurisdiction_type: field("texas_state"),
  deposition_date: field("2026-05-07"),
  start_time: field("10:00"),
  location: {
    address: field(""),
    city: field("San Antonio"),
    state: field("TX"),
    zip: field(""),
  },
  remote: { is_remote: field(true), platform: field("Zoom") },
  reporting_method: field("zoom"),
  witness: {
    name: field("Maria L. Lopez De Martinez"),
    role: field("witness"),
    party_affiliation: field("plaintiff"),
    read_and_sign: field(""),
    interpreter_required: field(false),
    videographer_required: field(false),
  },
  parties: [
    { name: field("Maria L. Lopez De Martinez"), role: field("plaintiff"), role_modifier: field(null), entity_type: field("individual"), fka_or_dba: field(null) },
    { name: field("Alfredo Montes Navarro"), role: field("plaintiff"), role_modifier: field(null), entity_type: field("individual"), fka_or_dba: field(null) },
    { name: field("Rafael Robles Calderon"), role: field("defendant"), role_modifier: field(null), entity_type: field("individual"), fka_or_dba: field(null) },
    { name: field("All American Heavy Equipment Leasing, LLC"), role: field("defendant"), role_modifier: field(null), entity_type: field("llc"), fka_or_dba: field(null) },
  ],
  attorneys: [],
  law_firms: [],
  scheduling: {
    proceeding_type: field("Remote Oral Deposition"),
    remote_platform: field("Zoom"),
    noticing_party: field("Plaintiff"),
    ordered_by: field("Goldman & Peterson, PLLC"),
    scheduler: field("Raul Garza"),
    scheduling_contact: field("Raul@LJGLaw.com"),
    service_type: field("CR_plus_Zoom"),
    time_zone: field("Central"),
    remote_location: field("San Antonio, Texas"),
  },
  service: {
    certificate_of_service: field(true),
    service_date: field("2026-04-20"),
    served_parties: field(["Counsel of Record"]),
    service_emails: field(["Raul@LJGLaw.com", "derek@tlegal.com"]),
  },
  reporter_requests: {
    certified_reporter_required: field(true),
    stenographic_recording: field(true),
    audiovisual_recording: field(false),
    realtime_requested: field(false),
    expedited_delivery: field(false),
    rush_delivery: field(false),
    daily_copy: field(false),
    rough_draft: field(false),
  },
};

export const ZOOM_NOD_FIXTURE: ExtractedNODFields = {
  ...FEDERAL_NOD_FIXTURE,
  scheduling: {
    ...FEDERAL_NOD_FIXTURE.scheduling,
    remote_platform: field("Teams"),
    proceeding_type: field("Remote Video Deposition"),
  },
  remote: {
    is_remote: field(true),
    platform: field("Teams"),
  },
};

export const MULTI_PARTY_NOD_FIXTURE: ExtractedNODFields = {
  ...FEDERAL_NOD_FIXTURE,
  parties: [
    ...FEDERAL_NOD_FIXTURE.parties,
    { name: field("Third Party Logistics, Inc."), role: field("third_party"), role_modifier: field(null), entity_type: field("corporation"), fka_or_dba: field(null) },
    { name: field("Cross Plaintiff Example, LLC"), role: field("cross_plaintiff"), role_modifier: field(null), entity_type: field("llc"), fka_or_dba: field(null) },
  ],
};
